import {enhanceSelect} from "./search-select.mjs";
import {selectProducts,addComparison,safeUrl,dimensions,scopedReviews,validateCatalog} from './logic.mjs';
const $=selector=>document.querySelector(selector);
const node=(tag,cls='',text='')=>{const e=document.createElement(tag);if(cls)e.className=cls;if(text)e.textContent=text;return e;};
const money=value=>value===null?'需詢價':`NT$${value.toLocaleString('zh-TW')}`;
const stateText={yes:'提供',no:'不提供',unknown:'待確認'};
const sourceKinds={official:'官方',retailer:'販售通路',independent:'使用者／獨立來源',sponsored:'業配／有誘因',secondary:'轉刊／間接來源'};
const action=(text,fn,cls='secondary')=>{const b=node('button',cls,text);b.type='button';b.addEventListener('click',fn);return b;};
const link=(text,url)=>{const href=safeUrl(url);if(!href)return node('span','',text);const a=node('a','',text);a.href=href;a.target='_blank';a.rel='noopener noreferrer';return a;};
let data,sourceMap,brandMap,visibleCount=24,results=[],selection=[],toastTimer;
function notify(message){clearTimeout(toastTimer);$('#toast').textContent=message;$('#toast').classList.add('visible');toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3200);}
function sourceList(ids){const list=node('div','source-list');for(const id of new Set(ids||[])){const s=sourceMap.get(id);if(!s)continue;const row=node('div');row.append(node('span','source-type',`${sourceKinds[s.kind]||'來源'} · ${s.checkedAt}`),link(s.title,s.url));list.append(row);}return list;}
function appendFacts(parent,pairs){const dl=node('dl','detail-grid');for(const [label,value] of pairs){dl.append(node('dt','',label),node('dd','',value||'未公開／待確認'));}parent.append(dl);}
function reviewFallback(product){const status=product.reviewSearch?.status;if(status==='checked')return '本次具名搜尋未找到可核實的型號負評；不代表沒有問題。';if(status==='limited')return product.reviewSearch.note||'已搜尋；部分原文無法讀取，型號心得證據有限。';return '型號心得尚待補齊，暫不判定好評或負評。';}
function negativeSummary(product,offer){const grouped=scopedReviews(data.reviews,product,offer);for(const [scope,label] of [['model','型號使用者反映'],['store','此門市服務反映'],['brand','品牌層級反映・非此型號判定']]){const r=grouped[scope].filter(x=>x.kind!=='positive').sort((a,b)=>(a.kind==='negative'?0:1)-(b.kind==='negative'?0:1))[0];if(r)return {label:label+(r.evidence==='sponsored'?'・有誘因心得':''),text:r.summary,negative:true};}return {label:'型號負評查核',text:reviewFallback(product),negative:false};}
function renderReviews(product,offer){const section=node('section');section.append(node('h4','','心得與負評'));const groups=scopedReviews(data.reviews,product,offer);for(const [key,title] of [['model','型號使用心得'],['brand','品牌售後／品牌心得'],['store','本通路／門市服務']]){section.append(node('h4','',title));if(!groups[key].length){section.append(node('p','small',key==='model'?reviewFallback(product):'本次未收錄可核實內容，不代表沒有問題。'));continue;}for(const r of groups[key]){const card=node('article',`review ${r.kind}`);const flag=r.evidence==='sponsored'?'業配／有誘因':r.evidence==='multiple'?'不同使用者重複反映':'單一個案';card.append(node('p','review-meta',`${flag} · 發表：${r.publishedAt||'原文未標日期'}`),node('p','',r.summary));if(r.resolution)card.append(node('p','',`後續／限制：${r.resolution}`));card.append(sourceList(r.sourceIds));section.append(card);}}
 if(product.reviewSearch){const d=node('details');d.append(node('summary','','查看型號查核範圍'),node('p','small',product.reviewSearch.note||'以具名型號搜尋公開心得，結果以可讀原文為準。'));const ul=node('ul');for(const q of product.reviewSearch.queries||[])ul.append(node('li','small',q));d.append(ul);section.append(d);}return section;}
function addToComparison(productId,offerId){const result=addComparison(selection,productId,offerId);if(result.status==='full'){notify('最多比較 4 個項目，請先移除一項。');return;}if(result.status==='duplicate'){notify('這個型號、尺寸與通路已在比較清單。');return;}renderDock();updateComparisonButtons();notify('已加入比較清單');}
function compareButton(product,offer,label='＋ 加入比較'){const b=action(label,()=>addToComparison(product.id,offer.id),'primary');b.dataset.product=product.id;b.dataset.offer=offer.id;return b;}
function updateComparisonButtons(){for(const b of document.querySelectorAll('button[data-product]')){const selected=selection.some(s=>s.productId===b.dataset.product&&s.offerId===b.dataset.offer);b.textContent=selected?'✓ 已加入比較':'＋ 加入比較';b.setAttribute('aria-pressed',String(selected));}}
function offerDetails(product,offer){const wrap=node('section','offer-detail');wrap.append(node('h4','',offer.name));const address=offer.address||(offer.channel==='online'?'網路通路，無對應試躺地址':'門市地址待確認');appendFacts(wrap,[['購買方式',offer.channel==='online'?'網路購買':'實體門市／展示點'],['床墊本體',`${money(offer.price)}${offer.priceNote?`；${offer.priceNote}`:''}`],['地址',address],['台中試躺',`${stateText[offer.trial]}；${offer.trialNote}`],['配送太平',`${stateText[offer.delivery]}；${offer.deliveryNote}`],['運費',offer.shippingNote],['搬樓層',offer.stairsNote],['舊床搬下樓',`${stateText[offer.downstairs]||'待確認'}；${offer.downstairsNote}`],['舊床載走',`${stateText[offer.haul]}${offer.haulFee!==null&&offer.haulFee!==undefined?` · ${money(offer.haulFee)}`:''}；${offer.haulNote}`],['居家試睡',offer.sleepTrial],['退換貨',offer.returns],['保固',offer.warranty]]);const links=node('div','card-actions');links.append(link('開啟商品／通路 ↗',offer.url));if(offer.address)links.append(link('查看地圖 ↗',`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(offer.address+' '+offer.name)}`));wrap.append(links,sourceList(offer.sourceIds),compareButton(product,offer));return wrap;}
function productCard(row){const {product,brand,bestOffer:offer,eligible}=row;const card=node('article','product-card');const body=node('div','card-body');const top=node('div','card-top');top.append(node('span','brand-name',brand.name),node('span',`badge ${eligible?'':'candidate'}`,eligible?`${product.size.system}雙人`:'條件待確認'));body.append(top,node('h3','',product.model),node('p','dimension-line',`${dimensions(product.size)} · ${product.size.label}`));const meta=node('div','product-meta');meta.append(node('span','',product.firmness.label||'軟硬待確認'),node('span','',(product.material||'結構待確認').length>55?`${product.material.slice(0,55)}…`:product.material||'結構待確認'));if(offer.trial==='yes')meta.append(node('span','','台中可試躺'));body.append(meta);if(product.scopeNote)body.append(node('p','small',product.scopeNote));const price=node('div','price-row');price.append(node('strong',row.price===null?'unknown-price':'',money(row.price)),node('small','','指定尺寸本體價'));body.append(price,node('p','offer-name',offer.name));const haul=node('div','haul-summary');haul.append(node('span','','舊床直接載走'),node('strong','',`${stateText[offer.haul]}${offer.haul==='yes'&&offer.haulFee!=null?` · ${money(offer.haulFee)}`:''}`));body.append(haul);const negative=negativeSummary(product,offer);const risk=node('div',`risk-box ${negative.negative?'':'neutral'}`);risk.append(node('strong','',negative.label),node('p','',negative.text));body.append(risk);const actions=node('div','card-actions');actions.append(compareButton(product,offer),link('商品來源 ↗',offer.url));body.append(actions);const detail=node('details','card-details');detail.append(node('summary','',`查看通路、負評與查核來源（${product.offers.length} 個通路）`));const contents=node('div','detail-body');let filled=false;detail.addEventListener('toggle',()=>{if(!detail.open||filled)return;filled=true;appendFacts(contents,[['實際尺寸',dimensions(product.size)],['結構',product.material],['官方躺感',product.firmness.label],['品牌主體',brand.entity]]);if(product.notes?.length){contents.append(node('h4','','規格／購買提醒'));const ul=node('ul');for(const n of product.notes)ul.append(node('li','',n));contents.append(ul);}contents.append(sourceList(product.sourceIds));for(const o of product.offers)contents.append(offerDetails(product,o));contents.append(renderReviews(product,offer));updateComparisonButtons();});detail.append(contents);card.append(body,detail);return card;}
function readFilters(){const values=Object.fromEntries(new FormData($('#filters')));values.sort=$('#sort').value;return values;}
function renderProducts(reset=true){if(reset)visibleCount=24;results=selectProducts(data,readFilters());$('#result-count').textContent=`${results.length.toLocaleString()} 款尺寸組合`;const f=readFilters();$('#results-note').textContent=f.status==='candidate'?'候選區：尺寸分類或配送條件尚未核實，請先確認再安排購買。':f.status==='all'?'全部收錄：主清單與候選並列，候選項目有明顯標記。':'依符合篩選的通路顯示最低公開本體價；需詢價置底。比較不限同品牌。';const target=$('#products');target.replaceChildren();if(!results.length){const empty=node('div','empty-state');empty.append(node('h3','','目前沒有符合的床墊'),node('p','','試著放寬價格、試躺或回收條件，也可以查看候選清單。'),action('清除篩選',resetFilters));target.append(empty);}else target.append(...results.slice(0,visibleCount).map(productCard));$('#load-more').hidden=results.length<=visibleCount;$('#load-more').textContent=`再看 ${Math.min(24,results.length-visibleCount)} 款（目前 ${Math.min(visibleCount,results.length)} / ${results.length}）`;updateComparisonButtons();}
function resetFilters(){$('#filters').reset();$('#sort').value='name';$('#sort').dispatchEvent(new Event('change'));}
function selectedItems(){return selection.map(s=>{const product=data.products.find(p=>p.id===s.productId);return {product,offer:product.offers.find(o=>o.id===s.offerId),brand:brandMap.get(product.brandId)};});}
function renderDock(){$('#compare-dock').hidden=!selection.length;$('#compare-count').textContent=`${selection.length} / 4`;$('#open-comparison').disabled=selection.length<2;const target=$('#compare-items');target.replaceChildren();for(const {product,offer} of selectedItems()){const chip=node('div','compare-chip');const label=`${product.model} · ${product.size.width||'?'}×${product.size.length||'?'}`;const text=node('span','',label);text.title=`${label} · ${offer.name}`;const remove=action('×',()=>{selection=selection.filter(s=>!(s.productId===product.id&&s.offerId===offer.id));renderDock();updateComparisonButtons();},'');remove.setAttribute('aria-label',`移除 ${label} ${offer.name}`);chip.append(text,remove);target.append(chip);}}
function compareReviewCell({product,offer}){const wrap=node('div');const summary=negativeSummary(product,offer);wrap.append(node('strong','',summary.label),node('p','',summary.text));wrap.append(renderReviews(product,offer));return wrap;}
function openComparison(){if(selection.length<2)return;const items=selectedItems();const table=node('table');const head=node('thead');const tr=node('tr');const corner=node('th','','比較項目');corner.scope='col';tr.append(corner);for(const x of items){const th=node('th');th.scope='col';th.append(node('small','',x.brand.name),node('strong','',x.product.model),node('small','',x.product.size.label));tr.append(th);}head.append(tr);table.append(head);const body=node('tbody');const rows=[['收錄資格',x=>[x.product.scopeStatus==='candidate'||x.product.size.system==='其他'||!x.product.size.width||!x.product.size.length||x.offer.delivery!=='yes'?'候選：條件待確認':'已確認尺寸與此通路配送',x.product.scopeNote||'',x.offer.delivery!=='yes'?x.offer.deliveryNote:''].filter(Boolean).join('；')],['實際尺寸',x=>dimensions(x.product.size)],['本體價格',x=>`${money(x.offer.price)}\n${x.offer.priceNote||''}`],['販售通路',x=>x.offer.name],['店面地址',x=>x.offer.address||(x.offer.channel==='online'?'網路通路，無實體地址':'待確認')],['軟硬／結構',x=>`${x.product.firmness.label}\n${x.product.material}`],['台中試躺',x=>`${stateText[x.offer.trial]}；${x.offer.trialNote}`],['負評與心得',compareReviewCell],['配送太平',x=>`${stateText[x.offer.delivery]}；${x.offer.deliveryNote}`],['運費／樓層',x=>`${x.offer.shippingNote}\n${x.offer.stairsNote}`],['舊床搬下樓',x=>`${stateText[x.offer.downstairs]||'待確認'}；${x.offer.downstairsNote}`],['舊床直接載走',x=>`${stateText[x.offer.haul]}${x.offer.haulFee!=null?` ${money(x.offer.haulFee)}`:''}；${x.offer.haulNote}`],['居家試睡',x=>x.offer.sleepTrial],['退換貨',x=>x.offer.returns],['保固',x=>x.offer.warranty],['備註',x=>x.product.notes.join('\n')||'—'],['查核來源',x=>sourceList([...x.product.sourceIds,...x.offer.sourceIds])]];for(const [title,get] of rows){const tr=node('tr');const label=node('th','',title);label.scope='row';tr.append(label);for(const x of items){const td=node('td',title==='負評與心得'?'negative-cell':'');const value=get(x);if(value instanceof Node)td.append(value);else for(const line of String(value||'待確認').split('\n'))td.append(node('p','',line));tr.append(td);}body.append(tr);}table.append(body);$('#comparison-content').replaceChildren(table);$('#comparison-dialog').showModal();}
function populateFilters(){const addOptions=(name,values)=>{const select=$(`[name="${name}"]`);for(const [value,label] of values){const option=node('option','',label);option.value=value;select.append(option);}};const collator=new Intl.Collator('zh-Hant',{numeric:true});addOptions('brand',data.brands.filter(b=>data.products.some(p=>p.brandId===b.id)).sort((a,b)=>collator.compare(a.name,b.name)).map(b=>[b.id,b.name]));const sizes=[...new Set(data.products.filter(p=>p.size.width&&p.size.length).map(p=>`${p.size.width}×${p.size.length}`))].sort(collator.compare);addOptions('size',sizes.map(s=>[s,s]));const districts=[...new Set(data.products.flatMap(p=>p.offers.map(o=>o.district)).filter(Boolean))].sort(collator.compare);addOptions('district',districts.map(d=>[d,d]));}
function renderStats(){const eligible=selectProducts(data,{});const variants=data.products.length;const models=new Set(data.products.map(p=>`${p.brandId}:${p.model}`)).size;const countedBrands=data.brands.length;const exact=eligible.filter(r=>r.price!==null).length;const sources=data.sources.length;const stats=[[countedBrands,'品牌已盤點','含候選及有理由排除的品牌'],[variants,'尺寸組合',`${models} 個型號・${eligible.length} 款確認尺寸及配送`],[exact,'款公開價格','僅計符合配送的指定尺寸報價'],[sources,'筆來源','規格、服務及心得分別留存']];$('#stats').replaceChildren(...stats.map(([number,label,description])=>{const d=node('div','stat');d.append(node('strong','',String(number)),node('span','',label),node('p','',description));return d;}));const latest=data.sources.map(s=>s.checkedAt).sort().at(-1)||data.research?.checkedAt||'';$('#checked-date').textContent=`資料查核：${latest} · 非即時報價`;}
function renderAudit(){$('#audit-intro').textContent=data.research?.note||'依品牌官方目錄與台中通路逐一盤點。未公開、無法讀取及尚待補齊的項目在下方明列，不以估計值填補。';const audits=new Map(data.audit.map(a=>[a.brandId,a]));const target=$('#audit-list');for(const brand of [...data.brands].sort((a,b)=>a.name.localeCompare(b.name,'zh-Hant'))){const a=audits.get(brand.id);const products=data.products.filter(p=>p.brandId===brand.id);const count=products.length;const details=node('details','audit-item');const summary=node('summary');summary.append(node('strong','',brand.name),node('span','small',`${count} 款尺寸組合`),node('span',`badge ${a?.status==='complete'?'':'candidate'}`,a?.status==='complete'?'型錄已核對':a?.status==='excluded'?'不符範圍':'部分待確認'));const content=node('div');content.append(node('p','',brand.entity||''),node('p','',brand.reason||''),node('p','',a?.notes||'型錄查核尚待補齊'),node('p','',`已讀商品頁紀錄（含重查）：${a?.productPagesChecked||0}；型號心得查核：${products.filter(p=>p.reviewSearch?.status==='checked').length} 款完成具名搜尋，${products.filter(p=>p.reviewSearch?.status==='limited').length} 款來源受限。`),sourceList(brand.sourceIds));if(a?.catalogUrls?.length){const d=node('div','source-list');for(const url of a.catalogUrls)d.append(link('官方分類／盤點入口 ↗',url));content.append(d);}if(a?.reviewQueries?.length){const q=node('details');q.append(node('summary','','查看品牌與型號搜尋紀錄'));const ul=node('ul');for(const query of a.reviewQueries)ul.append(node('li','',query));q.append(ul);content.append(q);}details.append(summary,content);target.append(details);}if(data.research?.rounds?.length){const d=node('details','audit-item');d.append(node('summary','','補漏搜尋紀錄'));const content=node('div');for(const round of data.research.rounds)content.append(node('p','',typeof round==='string'?round:JSON.stringify(round)));d.append(content);target.append(d);}}
async function init(){try{const response=await fetch('./catalog.json');if(!response.ok)throw new Error('目錄載入失敗');data=await response.json();const errors=validateCatalog(data);if(errors.length)throw new Error('目錄資料未通過檢查');sourceMap=new Map(data.sources.map(s=>[s.id,s]));brandMap=new Map(data.brands.map(b=>[b.id,b]));populateFilters();document.querySelectorAll("#filters select, #sort").forEach(enhanceSelect);renderStats();renderAudit();renderProducts();$('#filters').addEventListener('input',()=>renderProducts());$('#filters').addEventListener('submit',e=>e.preventDefault());$('#filters').addEventListener('reset',()=>queueMicrotask(()=>renderProducts()));$('#sort').addEventListener('change',()=>renderProducts());$('#load-more').addEventListener('click',()=>{visibleCount+=24;renderProducts(false);});$('#open-comparison').addEventListener('click',openComparison);$('#close-comparison').addEventListener('click',()=>$('#comparison-dialog').close());$('#clear-comparison').addEventListener('click',()=>{selection=[];renderDock();updateComparisonButtons();});if(matchMedia('(max-width:760px)').matches)$('#filter-panel').open=false;}catch{$('#stats').replaceChildren(node('p','','商品目錄暫時無法載入'));$('#products').replaceChildren(node('p','','請重新整理頁面，或下載完整查核資料查看。'));$('#result-count').textContent='目錄讀取失敗';}}
init();
